;*** Internal Memory ***
COMPONENT;
NAME=MEMORY;
ID=MEM;
BASEADDR=0;
ADDRWIDTH=8;
INTERRUPT=FALSE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\INT_MEMORY;
ENTITY=INT_MEMORY;
GENERICS=ADDRESS_WIDTH:8;
ENDCOMPONENT;

;*** Output Port ***
COMPONENT;
NAME=OUTPUT PORT;
ID=POUT;
BASEADDR=0100;
ADDRWIDTH=0;
INTERRUPT=FALSE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\OUTPUT_PORT;
ENTITY=OUTPUT_PORT;							
GENERICS=PORT_WIDTH:8;
EXTPORTS=POUT:PORT_WIDTH:OUT;
ENDCOMPONENT;

;*** Input Port ***
COMPONENT;
NAME=INPUT PORT;
ID=PIN;
BASEADDR=0110;
ADDRWIDTH=0;
INTERRUPT=FALSE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\INPUT_PORT;
ENTITY=INPUT_PORT;
GENERICS=PORT_WIDTH:8,SYNCHRONIZE:TRUE;
EXTPORTS=PIN:PORT_WIDTH:IN;
ENDCOMPONENT;

;*** Bidir Port ***
COMPONENT;
NAME=BIDIR PORT;
ID=PIO;
BASEADDR=0120;
ADDRWIDTH=2;
INTERRUPT=FALSE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\BIDIR_PORT;
ENTITY=BIDIR_PORT;
GENERICS=PORT_WIDTH:8,SYNCHRONIZE:TRUE;
EXTPORTS=PIO:PORT_WIDTH:INOUT;
ENDCOMPONENT;

;*** 8Bit Timer ***
COMPONENT;
NAME=8BIT TIMER;
ID=TMR8;
BASEADDR=0140;
ADDRWIDTH=2;
INTERRUPT=TRUE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\TIMER_8BIT;
ENTITY=TIMER_8BIT;
GENERICS=CLK_FREQUENCY:10000000,RESOLUTION_US:1000;
ENDCOMPONENT;

;*** 16Bit Timer ***
COMPONENT;
NAME=16BIT TIMER;
ID=TMR16;
BASEADDR=0160;
ADDRWIDTH=3;
INTERRUPT=TRUE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\TIMER_16BIT;
ENTITY=TIMER_16BIT;
GENERICS=CLK_FREQUENCY:10000000,RESOLUTION_US:1000;
ENDCOMPONENT;

;*** PWM Port ***
COMPONENT;
NAME=PWM PORT;
ID=PWM;
BASEADDR=0180;
ADDRWIDTH=0;
INTERRUPT=FALSE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\PWM_PORT;
ENTITY=PWM_PORT;
GENERICS=CLK_FREQUENCY:10000000,PWM_FREQUENCY:10000,PWM_RES_BITS:8;
EXTPORTS=PWM:1:OUT;
ENDCOMPONENT;

;*** External Interrupt ***
COMPONENT;
NAME=EXTERNAL INTERRUPT;
ID=INT;
BASEADDR=0190;
ADDRWIDTH=1;
INTERRUPT=TRUE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\EXT_INTERRUPT;
ENTITY=EXT_INTERRUPT;
GENERICS=SYNCHRONIZE:TRUE;
EXTPORTS=EXT_INT:1:IN;
ENDCOMPONENT;

;*** 16Bit System ID ***
COMPONENT;
NAME=16BIT SYSTEM ID;
ID=ID16;
BASEADDR=01A0;
ADDRWIDTH=1;
INTERRUPT=FALSE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\SYSTEMID_16BIT;
ENTITY=SYSTEMID_16BIT;
GENERICS=ID_HIGHBYTE:1,ID_LOWBYTE:0;
ENDCOMPONENT;

;*** Watchdog ***
COMPONENT;
NAME=WATCHDOG;
ID=WD;
BASEADDR=01B0;
ADDRWIDTH=1;
INTERRUPT=TRUE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\WATCHDOG;
ENTITY=WATCHDOG;
GENERICS=CLK_FREQUENCY:10000000,PERIOD_MS:1000;
EXTPORTS=TOUT_N:1:OUT;
ENDCOMPONENT;

;*** Simple RS-232 Port ***
COMPONENT;
NAME=SIMPLE RS232 PORT;
ID=RS232S;
BASEADDR=01C0;
ADDRWIDTH=2;
INTERRUPT=TRUE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\RS232_SIMPLE;
ENTITY=RS232_SIMPLE;
ADDSOURCEFILES=COMPORT.VHD;
GENERICS=CLK_FREQUENCY:10000000,BAUDRATE:9600;
EXTPORTS=RX:1:IN,TX:1:OUT;
ENDCOMPONENT;

;*** Buffered RS-232 Port ***
COMPONENT;
NAME=Buffered RS232 Port;
ID=RS232B;
BASEADDR=01D0;
ADDRWIDTH=2;
INTERRUPT=TRUE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\RS232_BUFFERED;
ENTITY=RS232_BUFFERED;
ADDSOURCEFILES=COMPORT.VHD;
GENERICS=CLK_FREQUENCY:10000000,BAUDRATE:9600,SNDBUF_SIZE:128,RECBUF_SIZE:128;
EXTPORTS=RX:1:IN,TX:1:OUT;
ENDCOMPONENT;

;*** LCD Interface ***
COMPONENT;
NAME=LCD Interface;
ID=LCD;
BASEADDR=01E0;
ADDRWIDTH=2;
INTERRUPT=TRUE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\LCD_SIMPLE;
ENTITY=LCD_SIMPLE;
GENERICS=CLK_FREQUENCY:10000000;
EXTPORTS=RS:1:OUT,RW:1:OUT,EN:1:OUT,DBUS:8:INOUT;
ENDCOMPONENT; ***
;*** 8-Bit FIFO
COMPONENT;
NAME=8BIT FIFO;
ID=FIFO;
BASEADDR=01F0;
ADDRWIDTH=2;
INTERRUPT=FALSE;
INPUTDATA=TRUE;
PATH=.\COMPONENTS\FIFO_8BIT;
ENTITY=FIFO_8BIT;
GENERICS=NUM_OF_FIFOS:4,SIZE_OF_FIFOS:64;
ENDCOMPONENT;

;COMPONENT
;NAME
;ID
;BASEADDR
;ADDRWIDTH
;INTERRUPT
;INPUTDATA
;PATH
;ENTITY
;ADDSOURCEFILES
;GENERICS
;EXTPORTS
;ENDCOMPONENT

;*** External Component ***
COMPONENT;
NAME=EXTERNAL COMPONENT;
ID=EXT;
BASEADDR=0200;
ADDRWIDTH=0;
INTERRUPT=FALSE;
INPUTDATA=TRUE;
GENERICS=;
EXTPORTS=;
ENDCOMPONENT;


ENDCDF;



